# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botFactory', '0002_auto_20170801_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bot_id',
            field=models.IntegerField(default=None),
        ),
    ]
