# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botFactory', '0004_auto_20170801_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bot',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botFactory.Account'),
        ),
    ]
