# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botFactory', '0005_auto_20170801_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botFactory.Account'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
